services:
  backend:
    image: edu-rag-backend:latest
    container_name: edu-rag-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    image: edu-rag-frontend:latest
    container_name: edu-rag-frontend
    restart: unless-stopped
    ports:
      - "3508:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
